# http://localhost:8081
axon-mongo-express:
  container_name: axon-mongo-express
  image: mongo-express
  environment:
    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ME_CONFIG_MONGODB_SERVER: axon-mongo
    ME_CONFIG_SITE_BASEURL: /
  ports:
    - "8081:8081"
  links:
    - axon-mongo
axon-mongo:
  container_name: axon-mongo
  image: mongo
  environment:
    - MONGO_PORT_27017_TCP_PORT=27017
  ports:
    - "27017:27017"
# http://localhost:8082
axon-rabbitmq:
   image: rabbitmq:3-management
   container_name: axon-rabbitmq-admin
   environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin
   ports:
     - "5672:5672"
     - "8082:15672"
     - "25672:25672"
